/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.0
// source: event.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./event_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.EventServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.EventServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.EventRequest,
 *   !proto.EventResponse>}
 */
const methodDescriptor_EventService_Unary = new grpc.web.MethodDescriptor(
  '/EventService/Unary',
  grpc.web.MethodType.UNARY,
  proto.EventRequest,
  proto.EventResponse,
  /**
   * @param {!proto.EventRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.EventResponse.deserializeBinary
);


/**
 * @param {!proto.EventRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.EventResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.EventResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.EventServiceClient.prototype.unary =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/EventService/Unary',
      request,
      metadata || {},
      methodDescriptor_EventService_Unary,
      callback);
};


/**
 * @param {!proto.EventRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.EventResponse>}
 *     Promise that resolves to the response
 */
proto.EventServicePromiseClient.prototype.unary =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/EventService/Unary',
      request,
      metadata || {},
      methodDescriptor_EventService_Unary);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.EventRequest,
 *   !proto.EventResponse>}
 */
const methodDescriptor_EventService_ServerStream = new grpc.web.MethodDescriptor(
  '/EventService/ServerStream',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.EventRequest,
  proto.EventResponse,
  /**
   * @param {!proto.EventRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.EventResponse.deserializeBinary
);


/**
 * @param {!proto.EventRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.EventResponse>}
 *     The XHR Node Readable Stream
 */
proto.EventServiceClient.prototype.serverStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/EventService/ServerStream',
      request,
      metadata || {},
      methodDescriptor_EventService_ServerStream);
};


/**
 * @param {!proto.EventRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.EventResponse>}
 *     The XHR Node Readable Stream
 */
proto.EventServicePromiseClient.prototype.serverStream =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/EventService/ServerStream',
      request,
      metadata || {},
      methodDescriptor_EventService_ServerStream);
};


module.exports = proto;

